apiVersion: v1
kind: Secret
metadata:
  name: pg-credentials
type: Opaque
stringData:
  # environment variables $PGUSER,$PGPASSWORD,$PGDATABASE gets replaced with 
  # values from environment
  url: 'postgres://$PGUSER:$PGPASSWORD@postgresql:5432/$PGDATABASE?sslmode=disable'